export interface DialogItem {
  id: string;
  category: 'presente' | 'perfecto' | 'indefinido' | 'imperfecto' | 'futuro' | 'drill';
  number: number;
  questionEs: string;
  questionHy: string;
  answerEs: string;
  answerHy: string;
  tenseTag: string;
  timeContext?: string; // e.g. "Ayer", "Hoy", "Mañana", "De pequeño"
}

export interface CategoryInfo {
  id: 'all' | 'presente' | 'perfecto' | 'indefinido' | 'imperfecto' | 'futuro' | 'drill';
  titleEs: string;
  titleHy: string;
  badge: string;
  description: string;
  color: string;
  count: number;
}

export const CATEGORIES: CategoryInfo[] = [
  {
    id: 'all',
    titleEs: 'Todos los tiempos',
    titleHy: 'Բոլոր ժամանակները',
    badge: '75+ հարց',
    description: 'Ամբողջական խոսակցական շտեմարան',
    color: 'from-amber-500 to-orange-600',
    count: 73,
  },
  {
    id: 'presente',
    titleEs: 'Presente',
    titleHy: 'Ներկա ժամանակ',
    badge: '20 երկխոսություն',
    description: 'Ամենօրյա գործողություններ, սովորություններ և առօրյա',
    color: 'from-emerald-500 to-teal-600',
    count: 20,
  },
  {
    id: 'perfecto',
    titleEs: 'Pretérito Perfecto',
    titleHy: 'Վերջերս կատարված անցյալ',
    badge: '10 երկխոսություն',
    description: 'Այսօր կամ այս շաբաթ տեղի ունեցած գործողություններ (hoy, esta semana)',
    color: 'from-blue-500 to-cyan-600',
    count: 10,
  },
  {
    id: 'indefinido',
    titleEs: 'Pretérito Indefinido',
    titleHy: 'Ավարտված անցյալ ժամանակ',
    badge: '20 երկխոսություն',
    description: 'Ավարտված կոնկրետ անցյալ իրադարձություններ (ayer, el fin de semana)',
    color: 'from-purple-500 to-indigo-600',
    count: 20,
  },
  {
    id: 'imperfecto',
    titleEs: 'Pretérito Imperfecto',
    titleHy: 'Սովորական անցյալ (անկատար)',
    badge: '10 երկխոսություն',
    description: 'Մանկության սովորույթներ, նկարագրություններ անցյալում (cuando era pequeño)',
    color: 'from-pink-500 to-rose-600',
    count: 10,
  },
  {
    id: 'futuro',
    titleEs: 'Futuro Simple',
    titleHy: 'Ապառնի պարզ ժամանակ',
    badge: '20 երկխոսություն',
    description: 'Վաղվա և ապագայի պլաններ ու մտադրություններ (mañana, en el futuro)',
    color: 'from-amber-500 to-red-500',
    count: 20,
  },
  {
    id: 'drill',
    titleEs: '⚡ Entrenamiento de Terminaciones',
    titleHy: '⚡ Ժամանակների համեմատություն',
    badge: 'Արագ մարզում',
    description: 'Նույն հարցը տարբեր ժամանակներով (Hoy / Ayer / Mañana)',
    color: 'from-violet-600 to-fuchsia-600',
    count: 3,
  },
];

export const DIALOGS_DATA: DialogItem[] = [
  // ================= PRESENTE (20) =================
  {
    id: 'pres-1',
    category: 'presente',
    number: 1,
    questionEs: '¿Qué haces por la mañana?',
    questionHy: 'Ի՞նչ ես անում առավոտյան։',
    answerEs: 'Me levanto, desayuno y voy al colegio.',
    answerHy: 'Արթնանում եմ, նախաճաշում և գնում դպրոց։',
    tenseTag: 'Presente',
    timeContext: 'por la mañana',
  },
  {
    id: 'pres-2',
    category: 'presente',
    number: 2,
    questionEs: '¿A qué hora te levantas normalmente?',
    questionHy: 'Սովորաբար ժամը քանի՞սին ես արթնանում։',
    answerEs: 'Me levanto a las siete.',
    answerHy: 'Արթնանում եմ ժամը յոթին։',
    tenseTag: 'Presente',
    timeContext: 'normalmente',
  },
  {
    id: 'pres-3',
    category: 'presente',
    number: 3,
    questionEs: '¿Qué desayunas?',
    questionHy: 'Ի՞նչ ես նախաճաշում։',
    answerEs: 'Desayuno pan, queso y té.',
    answerHy: 'Նախաճաշում եմ հաց, պանիր և թեյ։',
    tenseTag: 'Presente',
  },
  {
    id: 'pres-4',
    category: 'presente',
    number: 4,
    questionEs: '¿Cómo vas al colegio?',
    questionHy: 'Ինչպե՞ս ես գնում դպրոց։',
    answerEs: 'Voy en autobús.',
    answerHy: 'Գնում եմ ավտոբուսով։',
    tenseTag: 'Presente',
  },
  {
    id: 'pres-5',
    category: 'presente',
    number: 5,
    questionEs: '¿Qué asignatura te gusta más?',
    questionHy: 'Ո՞ր առարկան ես ամենաշատը սիրում։',
    answerEs: 'Me gusta más la historia.',
    answerHy: 'Ամենաշատը սիրում եմ պատմությունը։',
    tenseTag: 'Presente',
  },
  {
    id: 'pres-6',
    category: 'presente',
    number: 6,
    questionEs: '¿Qué haces después de clase?',
    questionHy: 'Ի՞նչ ես անում դասերից հետո։',
    answerEs: 'Vuelvo a casa y hago los deberes.',
    answerHy: 'Վերադառնում եմ տուն և անում տնային աշխատանքը։',
    tenseTag: 'Presente',
    timeContext: 'después de clase',
  },
  {
    id: 'pres-7',
    category: 'presente',
    number: 7,
    questionEs: '¿Practicas algún deporte?',
    questionHy: 'Որևէ սպորտով զբաղվո՞ւմ ես։',
    answerEs: 'Sí, juego al fútbol dos veces por semana.',
    answerHy: 'Այո, շաբաթը երկու անգամ ֆուտբոլ եմ խաղում։',
    tenseTag: 'Presente',
  },
  {
    id: 'pres-8',
    category: 'presente',
    number: 8,
    questionEs: '¿Qué haces en tu tiempo libre?',
    questionHy: 'Ի՞նչ ես անում ազատ ժամանակ։',
    answerEs: 'Escucho música y veo películas.',
    answerHy: 'Երաժշտություն եմ լսում և ֆիլմեր եմ դիտում։',
    tenseTag: 'Presente',
    timeContext: 'en tu tiempo libre',
  },
  {
    id: 'pres-9',
    category: 'presente',
    number: 9,
    questionEs: '¿Ayudas en casa?',
    questionHy: 'Տանը օգնո՞ւմ ես։',
    answerEs: 'Sí, limpio mi habitación y pongo la mesa.',
    answerHy: 'Այո, մաքրում եմ սենյակս և սեղանն եմ պատրաստում։',
    tenseTag: 'Presente',
  },
  {
    id: 'pres-10',
    category: 'presente',
    number: 10,
    questionEs: '¿Qué comes normalmente al mediodía?',
    questionHy: 'Սովորաբար ի՞նչ ես ուտում կեսօրին։',
    answerEs: 'Como arroz, pollo o pasta.',
    answerHy: 'Ուտում եմ բրինձ, հավ կամ մակարոն։',
    tenseTag: 'Presente',
    timeContext: 'al mediodía',
  },
  {
    id: 'pres-11',
    category: 'presente',
    number: 11,
    questionEs: '¿Qué fruta comes más?',
    questionHy: 'Ո՞ր միրգն ես ամենաշատը ուտում։',
    answerEs: 'Como muchas manzanas y plátanos.',
    answerHy: 'Շատ խնձոր և բանան եմ ուտում։',
    tenseTag: 'Presente',
  },
  {
    id: 'pres-12',
    category: 'presente',
    number: 12,
    questionEs: '¿Qué haces los sábados?',
    questionHy: 'Ի՞նչ ես անում շաբաթ օրերին։',
    answerEs: 'Salgo con mis amigos o descanso en casa.',
    answerHy: 'Դուրս եմ գալիս ընկերներիս հետ կամ հանգստանում եմ տանը։',
    tenseTag: 'Presente',
    timeContext: 'los sábados',
  },
  {
    id: 'pres-13',
    category: 'presente',
    number: 13,
    questionEs: '¿Con quién hablas más durante el día?',
    questionHy: 'Օրվա ընթացքում ո՞ւմ հետ ես ամենաշատը խոսում։',
    answerEs: 'Hablo mucho con mis amigos.',
    answerHy: 'Շատ եմ խոսում ընկերներիս հետ։',
    tenseTag: 'Presente',
  },
  {
    id: 'pres-14',
    category: 'presente',
    number: 14,
    questionEs: '¿Usas mucho el móvil?',
    questionHy: 'Շա՞տ ես օգտագործում հեռախոսը։',
    answerEs: 'Sí, lo uso para hablar y estudiar.',
    answerHy: 'Այո, օգտագործում եմ խոսելու և սովորելու համար։',
    tenseTag: 'Presente',
  },
  {
    id: 'pres-15',
    category: 'presente',
    number: 15,
    questionEs: '¿Qué ropa llevas normalmente?',
    questionHy: 'Սովորաբար ի՞նչ հագուստ ես կրում։',
    answerEs: 'Llevo vaqueros, camiseta y zapatillas.',
    answerHy: 'Կրում եմ ջինս, շապիկ և սպորտային կոշիկներ։',
    tenseTag: 'Presente',
  },
  {
    id: 'pres-16',
    category: 'presente',
    number: 16,
    questionEs: '¿Te gusta cocinar?',
    questionHy: 'Սիրո՞ւմ ես պատրաստել։',
    answerEs: 'Sí, preparo cosas sencillas.',
    answerHy: 'Այո, պարզ ուտեստներ եմ պատրաստում։',
    tenseTag: 'Presente',
  },
  {
    id: 'pres-17',
    category: 'presente',
    number: 17,
    questionEs: '¿Qué compras normalmente en el supermercado?',
    questionHy: 'Սովորաբար ի՞նչ ես գնում սուպերմարկետում։',
    answerEs: 'Compro fruta, leche, pan y verduras.',
    answerHy: 'Գնում եմ միրգ, կաթ, հաց և բանջարեղեն։',
    tenseTag: 'Presente',
  },
  {
    id: 'pres-18',
    category: 'presente',
    number: 18,
    questionEs: '¿A qué hora cenas?',
    questionHy: 'Ժամը քանի՞սին ես ընթրում։',
    answerEs: 'Ceno a las ocho y media.',
    answerHy: 'Ընթրում եմ ժամը ութն անց կես։',
    tenseTag: 'Presente',
  },
  {
    id: 'pres-19',
    category: 'presente',
    number: 19,
    questionEs: '¿Lees antes de dormir?',
    questionHy: 'Քնելուց առաջ կարդո՞ւմ ես։',
    answerEs: 'A veces leo un poco.',
    answerHy: 'Երբեմն մի քիչ կարդում եմ։',
    tenseTag: 'Presente',
    timeContext: 'antes de dormir',
  },
  {
    id: 'pres-20',
    category: 'presente',
    number: 20,
    questionEs: '¿A qué hora te acuestas?',
    questionHy: 'Ժամը քանի՞սին ես քնում։',
    answerEs: 'Me acuesto sobre las diez y media.',
    answerHy: 'Քնում եմ մոտավորապես ժամը տասը անց կես։',
    tenseTag: 'Presente',
  },

  // ================= PRETÉRITO PERFECTO (10) =================
  {
    id: 'perf-1',
    category: 'perfecto',
    number: 1,
    questionEs: '¿Qué has hecho hoy?',
    questionHy: 'Ի՞նչ ես արել այսօր։',
    answerEs: 'He ido al colegio y he estudiado.',
    answerHy: 'Գնացել եմ դպրոց և սովորել եմ։',
    tenseTag: 'Pretérito Perfecto',
    timeContext: 'hoy',
  },
  {
    id: 'perf-2',
    category: 'perfecto',
    number: 2,
    questionEs: '¿Has desayunado hoy?',
    questionHy: 'Այսօր նախաճաշե՞լ ես։',
    answerEs: 'Sí, he desayunado antes de salir.',
    answerHy: 'Այո, նախաճաշել եմ դուրս գալուց առաջ։',
    tenseTag: 'Pretérito Perfecto',
    timeContext: 'hoy',
  },
  {
    id: 'perf-3',
    category: 'perfecto',
    number: 3,
    questionEs: '¿Has hablado con tus amigos hoy?',
    questionHy: 'Այսօր խոսե՞լ ես ընկերներիդ հետ։',
    answerEs: 'Sí, he hablado con ellos en el colegio.',
    answerHy: 'Այո, նրանց հետ խոսել եմ դպրոցում։',
    tenseTag: 'Pretérito Perfecto',
    timeContext: 'hoy',
  },
  {
    id: 'perf-4',
    category: 'perfecto',
    number: 4,
    questionEs: '¿Qué has comido hoy?',
    questionHy: 'Ի՞նչ ես կերել այսօր։',
    answerEs: 'He comido pollo con arroz.',
    answerHy: 'Կերել եմ հավ բրնձով։',
    tenseTag: 'Pretérito Perfecto',
    timeContext: 'hoy',
  },
  {
    id: 'perf-5',
    category: 'perfecto',
    number: 5,
    questionEs: '¿Has visto alguna película esta semana?',
    questionHy: 'Այս շաբաթ որևէ ֆիլմ տեսե՞լ ես։',
    answerEs: 'Sí, he visto una película de comedia.',
    answerHy: 'Այո, կատակերգական ֆիլմ եմ դիտել։',
    tenseTag: 'Pretérito Perfecto',
    timeContext: 'esta semana',
  },
  {
    id: 'perf-6',
    category: 'perfecto',
    number: 6,
    questionEs: '¿Has hecho deporte esta semana?',
    questionHy: 'Այս շաբաթ սպորտով զբաղվե՞լ ես։',
    answerEs: 'Sí, he jugado al fútbol dos veces.',
    answerHy: 'Այո, երկու անգամ ֆուտբոլ եմ խաղացել։',
    tenseTag: 'Pretérito Perfecto',
    timeContext: 'esta semana',
  },
  {
    id: 'perf-7',
    category: 'perfecto',
    number: 7,
    questionEs: '¿Has comprado algo hoy?',
    questionHy: 'Այսօր որևէ բան գնե՞լ ես։',
    answerEs: 'Sí, he comprado una botella de agua.',
    answerHy: 'Այո, մեկ շիշ ջուր եմ գնել։',
    tenseTag: 'Pretérito Perfecto',
    timeContext: 'hoy',
  },
  {
    id: 'perf-8',
    category: 'perfecto',
    number: 8,
    questionEs: '¿Has terminado los deberes?',
    questionHy: 'Ավարտե՞լ ես տնային աշխատանքը։',
    answerEs: 'Sí, ya los he terminado.',
    answerHy: 'Այո, արդեն ավարտել եմ։',
    tenseTag: 'Pretérito Perfecto',
  },
  {
    id: 'perf-9',
    category: 'perfecto',
    number: 9,
    questionEs: '¿Has aprendido algo nuevo hoy?',
    questionHy: 'Այսօր նոր բան սովորե՞լ ես։',
    answerEs: 'Sí, he aprendido palabras nuevas en español.',
    answerHy: 'Այո, իսպաներեն նոր բառեր եմ սովորել։',
    tenseTag: 'Pretérito Perfecto',
    timeContext: 'hoy',
  },
  {
    id: 'perf-10',
    category: 'perfecto',
    number: 10,
    questionEs: '¿Has hablado español hoy?',
    questionHy: 'Այսօր իսպաներեն խոսե՞լ ես։',
    answerEs: 'Sí, he hablado español en clase.',
    answerHy: 'Այո, դասին իսպաներեն եմ խոսել։',
    tenseTag: 'Pretérito Perfecto',
    timeContext: 'hoy',
  },

  // ================= PRETÉRITO INDEFINIDO (20) =================
  {
    id: 'indef-1',
    category: 'indefinido',
    number: 1,
    questionEs: '¿Qué hiciste ayer después de clase?',
    questionHy: 'Ի՞նչ արեցիր երեկ դասերից հետո։',
    answerEs: 'Fui a casa, comí y descansé un poco.',
    answerHy: 'Գնացի տուն, կերա և մի քիչ հանգստացա։',
    tenseTag: 'Pretérito Indefinido',
    timeContext: 'ayer después de clase',
  },
  {
    id: 'indef-2',
    category: 'indefinido',
    number: 2,
    questionEs: '¿A qué hora te levantaste ayer?',
    questionHy: 'Երեկ ժամը քանի՞սին արթնացար։',
    answerEs: 'Me levanté a las siete y media.',
    answerHy: 'Արթնացա ժամը յոթ անց կես։',
    tenseTag: 'Pretérito Indefinido',
    timeContext: 'ayer',
  },
  {
    id: 'indef-3',
    category: 'indefinido',
    number: 3,
    questionEs: '¿Qué desayunaste esta mañana?',
    questionHy: 'Այսօր առավոտյան ի՞նչ նախաճաշեցիր։',
    answerEs: 'Desayuné pan, queso y té.',
    answerHy: 'Նախաճաշեցի հաց, պանիր և թեյ։',
    tenseTag: 'Pretérito Indefinido',
    timeContext: 'esta mañana',
  },
  {
    id: 'indef-4',
    category: 'indefinido',
    number: 4,
    questionEs: '¿Cómo fuiste al colegio ayer?',
    questionHy: 'Երեկ ինչպե՞ս գնացիր դպրոց։',
    answerEs: 'Fui en autobús.',
    answerHy: 'Գնացի ավտոբուսով։',
    tenseTag: 'Pretérito Indefinido',
    timeContext: 'ayer',
  },
  {
    id: 'indef-5',
    category: 'indefinido',
    number: 5,
    questionEs: '¿Con quién hablaste ayer?',
    questionHy: 'Երեկ ո՞ւմ հետ խոսեցիր։',
    answerEs: 'Hablé con mis amigos y con mi profesor.',
    answerHy: 'Խոսեցի ընկերներիս և ուսուցչիս հետ։',
    tenseTag: 'Pretérito Indefinido',
    timeContext: 'ayer',
  },
  {
    id: 'indef-6',
    category: 'indefinido',
    number: 6,
    questionEs: '¿Qué comiste al mediodía?',
    questionHy: 'Կեսօրին ի՞նչ կերար։',
    answerEs: 'Comí arroz con pollo y ensalada.',
    answerHy: 'Կերա բրինձ հավով և աղցան։',
    tenseTag: 'Pretérito Indefinido',
    timeContext: 'al mediodía',
  },
  {
    id: 'indef-7',
    category: 'indefinido',
    number: 7,
    questionEs: '¿Compraste algo ayer?',
    questionHy: 'Երեկ որևէ բան գնեցի՞ր։',
    answerEs: 'Sí, compré fruta y una botella de agua.',
    answerHy: 'Այո, միրգ և մեկ շիշ ջուր գնեցի։',
    tenseTag: 'Pretérito Indefinido',
    timeContext: 'ayer',
  },
  {
    id: 'indef-8',
    category: 'indefinido',
    number: 8,
    questionEs: '¿Fuiste al supermercado esta semana?',
    questionHy: 'Այս շաբաթ սուպերմարկետ գնացի՞ր։',
    answerEs: 'Sí, fui con mi familia.',
    answerHy: 'Այո, գնացի ընտանիքիս հետ։',
    tenseTag: 'Pretérito Indefinido',
    timeContext: 'esta semana',
  },
  {
    id: 'indef-9',
    category: 'indefinido',
    number: 9,
    questionEs: '¿Qué compraste allí?',
    questionHy: 'Այնտեղ ի՞նչ գնեցիր։',
    answerEs: 'Compré manzanas, plátanos y leche.',
    answerHy: 'Գնեցի խնձոր, բանան և կաթ։',
    tenseTag: 'Pretérito Indefinido',
  },
  {
    id: 'indef-10',
    category: 'indefinido',
    number: 10,
    questionEs: '¿Viste una película el fin de semana?',
    questionHy: 'Հանգստյան օրերին ֆիլմ դիտեցի՞ր։',
    answerEs: 'Sí, vi una comedia.',
    answerHy: 'Այո, կատակերգություն դիտեցի։',
    tenseTag: 'Pretérito Indefinido',
    timeContext: 'el fin de semana',
  },
  {
    id: 'indef-11',
    category: 'indefinido',
    number: 11,
    questionEs: '¿Te gustó la película?',
    questionHy: 'Ֆիլմը քեզ դո՞ւր եկավ։',
    answerEs: 'Sí, me gustó mucho.',
    answerHy: 'Այո, շատ դուր եկավ։',
    tenseTag: 'Pretérito Indefinido',
  },
  {
    id: 'indef-12',
    category: 'indefinido',
    number: 12,
    questionEs: '¿Jugaste al fútbol la semana pasada?',
    questionHy: 'Անցյալ շաբաթ ֆուտբոլ խաղացի՞ր։',
    answerEs: 'Sí, jugué con mis amigos.',
    answerHy: 'Այո, խաղացի ընկերներիս հետ։',
    tenseTag: 'Pretérito Indefinido',
    timeContext: 'la semana pasada',
  },
  {
    id: 'indef-13',
    category: 'indefinido',
    number: 13,
    questionEs: '¿Dónde pasaste el fin de semana?',
    questionHy: 'Որտե՞ղ անցկացրիր հանգստյան օրերը։',
    answerEs: 'Lo pasé en casa con mi familia.',
    answerHy: 'Այն անցկացրի տանը՝ ընտանիքիս հետ։',
    tenseTag: 'Pretérito Indefinido',
    timeContext: 'el fin de semana',
  },
  {
    id: 'indef-14',
    category: 'indefinido',
    number: 14,
    questionEs: '¿A quién llamaste ayer?',
    questionHy: 'Երեկ ո՞ւմ զանգեցիր։',
    answerEs: 'Llamé a un amigo.',
    answerHy: 'Զանգեցի ընկերոջս։',
    tenseTag: 'Pretérito Indefinido',
    timeContext: 'ayer',
  },
  {
    id: 'indef-15',
    category: 'indefinido',
    number: 15,
    questionEs: '¿Qué estudiaste ayer?',
    questionHy: 'Երեկ ի՞նչ սովորեցիր։',
    answerEs: 'Estudié español e historia.',
    answerHy: 'Սովորեցի իսպաներեն և պատմություն։',
    tenseTag: 'Pretérito Indefinido',
    timeContext: 'ayer',
  },
  {
    id: 'indef-16',
    category: 'indefinido',
    number: 16,
    questionEs: '¿Terminaste tus deberes?',
    questionHy: 'Ավարտեցի՞ր տնային աշխատանքդ։',
    answerEs: 'Sí, los terminé por la tarde.',
    answerHy: 'Այո, ավարտեցի կեսօրից հետո։',
    tenseTag: 'Pretérito Indefinido',
  },
  {
    id: 'indef-17',
    category: 'indefinido',
    number: 17,
    questionEs: '¿Saliste con tus amigos el sábado?',
    questionHy: 'Շաբաթ օրը ընկերներիդ հետ դուրս եկա՞ր։',
    answerEs: 'Sí, salimos al centro.',
    answerHy: 'Այո, գնացինք կենտրոն։',
    tenseTag: 'Pretérito Indefinido',
    timeContext: 'el sábado',
  },
  {
    id: 'indef-18',
    category: 'indefinido',
    number: 18,
    questionEs: '¿Qué hiciste allí?',
    questionHy: 'Այնտեղ ի՞նչ արեցիր։',
    answerEs: 'Caminamos, hablamos y comimos algo.',
    answerHy: 'Քայլեցինք, խոսեցինք և ինչ-որ բան կերանք։',
    tenseTag: 'Pretérito Indefinido',
  },
  {
    id: 'indef-19',
    category: 'indefinido',
    number: 19,
    questionEs: '¿A qué hora volviste a casa?',
    questionHy: 'Ժամը քանի՞սին վերադարձար տուն։',
    answerEs: 'Volví a casa a las nueve.',
    answerHy: 'Տուն վերադարձա ժամը իննին։',
    tenseTag: 'Pretérito Indefinido',
  },
  {
    id: 'indef-20',
    category: 'indefinido',
    number: 20,
    questionEs: '¿Qué cenaste anoche?',
    questionHy: 'Երեկ երեկոյան ի՞նչ ընթրեցիր։',
    answerEs: 'Cené pasta y verduras.',
    answerHy: 'Ընթրեցի մակարոն և բանջարեղեն։',
    tenseTag: 'Pretérito Indefinido',
    timeContext: 'anoche',
  },

  // ================= PRETÉRITO IMPERFECTO (10) =================
  {
    id: 'imp-1',
    category: 'imperfecto',
    number: 1,
    questionEs: '¿Qué hacías después del colegio cuando eras pequeño?',
    questionHy: 'Ի՞նչ էիր անում դպրոցից հետո, երբ փոքր էիր։',
    answerEs: 'Jugaba con mis amigos.',
    answerHy: 'Խաղում էի ընկերներիս հետ։',
    tenseTag: 'Pretérito Imperfecto',
    timeContext: 'cuando eras pequeño',
  },
  {
    id: 'imp-2',
    category: 'imperfecto',
    number: 2,
    questionEs: '¿Dónde vivías de pequeño?',
    questionHy: 'Որտե՞ղ էիր ապրում փոքր ժամանակ։',
    answerEs: 'Vivía en una ciudad pequeña.',
    answerHy: 'Ապրում էի փոքր քաղաքում։',
    tenseTag: 'Pretérito Imperfecto',
    timeContext: 'de pequeño',
  },
  {
    id: 'imp-3',
    category: 'imperfecto',
    number: 3,
    questionEs: '¿Qué dibujos animados veías?',
    questionHy: 'Ի՞նչ մուլտֆիլմեր էիր դիտում։',
    answerEs: 'Veía dibujos animados por la tarde.',
    answerHy: 'Կեսօրից հետո մուլտֆիլմեր էի դիտում։',
    tenseTag: 'Pretérito Imperfecto',
  },
  {
    id: 'imp-4',
    category: 'imperfecto',
    number: 4,
    questionEs: '¿Con quién jugabas?',
    questionHy: 'Ո՞ւմ հետ էիր խաղում։',
    answerEs: 'Jugaba con mis amigos y mis primos.',
    answerHy: 'Խաղում էի ընկերներիս և զարմիկներիս հետ։',
    tenseTag: 'Pretérito Imperfecto',
  },
  {
    id: 'imp-5',
    category: 'imperfecto',
    number: 5,
    questionEs: '¿Qué comida te gustaba?',
    questionHy: 'Ի՞նչ ուտելիք էիր սիրում։',
    answerEs: 'Me gustaba mucho la pasta.',
    answerHy: 'Շատ էի սիրում մակարոն։',
    tenseTag: 'Pretérito Imperfecto',
  },
  {
    id: 'imp-6',
    category: 'imperfecto',
    number: 6,
    questionEs: '¿Ibas mucho al parque?',
    questionHy: 'Շա՞տ էիր գնում այգի։',
    answerEs: 'Sí, iba casi todos los días.',
    answerHy: 'Այո, գրեթե ամեն օր գնում էի։',
    tenseTag: 'Pretérito Imperfecto',
  },
  {
    id: 'imp-7',
    category: 'imperfecto',
    number: 7,
    questionEs: '¿Leías libros de pequeño?',
    questionHy: 'Փոքր ժամանակ գրքեր կարդո՞ւմ էիր։',
    answerEs: 'Sí, leía cuentos.',
    answerHy: 'Այո, հեքիաթներ էի կարդում։',
    tenseTag: 'Pretérito Imperfecto',
    timeContext: 'de pequeño',
  },
  {
    id: 'imp-8',
    category: 'imperfecto',
    number: 8,
    questionEs: '¿Qué deporte practicabas?',
    questionHy: 'Ի՞նչ սպորտով էիր զբաղվում։',
    answerEs: 'Practicaba fútbol.',
    answerHy: 'Ֆուտբոլով էի զբաղվում։',
    tenseTag: 'Pretérito Imperfecto',
  },
  {
    id: 'imp-9',
    category: 'imperfecto',
    number: 9,
    questionEs: '¿Cómo era tu colegio?',
    questionHy: 'Ինչպիսի՞ն էր քո դպրոցը։',
    answerEs: 'Era grande y tenía un patio enorme.',
    answerHy: 'Այն մեծ էր և ուներ մեծ բակ։',
    tenseTag: 'Pretérito Imperfecto',
  },
  {
    id: 'imp-10',
    category: 'imperfecto',
    number: 10,
    questionEs: '¿Qué hacías los domingos?',
    questionHy: 'Ի՞նչ էիր անում կիրակի օրերին։',
    answerEs: 'Pasaba tiempo con mi familia.',
    answerHy: 'Ժամանակ էի անցկացնում ընտանիքիս հետ։',
    tenseTag: 'Pretérito Imperfecto',
    timeContext: 'los domingos',
  },

  // ================= FUTURO SIMPLE (20) =================
  {
    id: 'fut-1',
    category: 'futuro',
    number: 1,
    questionEs: '¿Qué harás mañana por la mañana?',
    questionHy: 'Ի՞նչ կանես վաղը առավոտյան։',
    answerEs: 'Me levantaré temprano y desayunaré.',
    answerHy: 'Շուտ կարթնանամ և կնախաճաշեմ։',
    tenseTag: 'Futuro Simple',
    timeContext: 'mañana por la mañana',
  },
  {
    id: 'fut-2',
    category: 'futuro',
    number: 2,
    questionEs: '¿Adónde irás mañana?',
    questionHy: 'Ո՞ւր կգնաս վաղը։',
    answerEs: 'Iré al colegio y después volveré a casa.',
    answerHy: 'Կգնամ դպրոց, հետո կվերադառնամ տուն։',
    tenseTag: 'Futuro Simple',
    timeContext: 'mañana',
  },
  {
    id: 'fut-3',
    category: 'futuro',
    number: 3,
    questionEs: '¿Qué estudiarás esta tarde?',
    questionHy: 'Ի՞նչ կսովորես այսօր կեսօրից հետո։',
    answerEs: 'Estudiaré español y ciencias.',
    answerHy: 'Կսովորեմ իսպաներեն և բնագիտություն։',
    tenseTag: 'Futuro Simple',
    timeContext: 'esta tarde',
  },
  {
    id: 'fut-4',
    category: 'futuro',
    number: 4,
    questionEs: '¿Qué comerás mañana?',
    questionHy: 'Ի՞նչ կուտես վաղը։',
    answerEs: 'Comeré pollo con arroz.',
    answerHy: 'Կուտեմ հավ բրնձով։',
    tenseTag: 'Futuro Simple',
    timeContext: 'mañana',
  },
  {
    id: 'fut-5',
    category: 'futuro',
    number: 5,
    questionEs: '¿Harás los deberes esta tarde?',
    questionHy: 'Այսօր կեսօրից հետո տնային աշխատանքը կանե՞ս։',
    answerEs: 'Sí, los haré después de comer.',
    answerHy: 'Այո, կանեմ ուտելուց հետո։',
    tenseTag: 'Futuro Simple',
    timeContext: 'esta tarde',
  },
  {
    id: 'fut-6',
    category: 'futuro',
    number: 6,
    questionEs: '¿Qué harás el sábado?',
    questionHy: 'Ի՞նչ կանես շաբաթ օրը։',
    answerEs: 'Saldré con mis amigos.',
    answerHy: 'Դուրս կգամ ընկերներիս հետ։',
    tenseTag: 'Futuro Simple',
    timeContext: 'el sábado',
  },
  {
    id: 'fut-7',
    category: 'futuro',
    number: 7,
    questionEs: '¿Jugarás al fútbol este fin de semana?',
    questionHy: 'Այս հանգստյան օրերին ֆուտբոլ կխաղա՞ս։',
    answerEs: 'Sí, jugaré el domingo.',
    answerHy: 'Այո, կխաղամ կիրակի օրը։',
    tenseTag: 'Futuro Simple',
    timeContext: 'este fin de semana',
  },
  {
    id: 'fut-8',
    category: 'futuro',
    number: 8,
    questionEs: '¿Verás alguna película esta noche?',
    questionHy: 'Այս երեկո որևէ ֆիլմ կդիտե՞ս։',
    answerEs: 'Sí, veré una película después de cenar.',
    answerHy: 'Այո, ընթրիքից հետո ֆիլմ կդիտեմ։',
    tenseTag: 'Futuro Simple',
    timeContext: 'esta noche',
  },
  {
    id: 'fut-9',
    category: 'futuro',
    number: 9,
    questionEs: '¿Qué comprarás la próxima vez que vayas de compras?',
    questionHy: 'Հաջորդ անգամ գնումների գնալիս ի՞նչ կգնես։',
    answerEs: 'Compraré unas zapatillas nuevas.',
    answerHy: 'Նոր սպորտային կոշիկներ կգնեմ։',
    tenseTag: 'Futuro Simple',
  },
  {
    id: 'fut-10',
    category: 'futuro',
    number: 10,
    questionEs: '¿Con quién pasarás el fin de semana?',
    questionHy: 'Ո՞ւմ հետ կանցկացնես հանգստյան օրերը։',
    answerEs: 'Lo pasaré con mi familia.',
    answerHy: 'Կանցկացնեմ ընտանիքիս հետ։',
    tenseTag: 'Futuro Simple',
    timeContext: 'el fin de semana',
  },
  {
    id: 'fut-11',
    category: 'futuro',
    number: 11,
    questionEs: '¿Qué fruta comprarás mañana?',
    questionHy: 'Վաղը ի՞նչ միրգ կգնես։',
    answerEs: 'Compraré manzanas y naranjas.',
    answerHy: 'Կգնեմ խնձոր և նարինջ։',
    tenseTag: 'Futuro Simple',
    timeContext: 'mañana',
  },
  {
    id: 'fut-12',
    category: 'futuro',
    number: 12,
    questionEs: '¿A qué hora volverás a casa mañana?',
    questionHy: 'Վաղը ժամը քանի՞սին կվերադառնաս տուն։',
    answerEs: 'Volveré a las seis.',
    answerHy: 'Կվերադառնամ ժամը վեցին։',
    tenseTag: 'Futuro Simple',
    timeContext: 'mañana',
  },
  {
    id: 'fut-13',
    category: 'futuro',
    number: 13,
    questionEs: '¿Hablarás español mañana en clase?',
    questionHy: 'Վաղը դասին իսպաներեն կխոսե՞ս։',
    answerEs: 'Sí, intentaré hablar más español.',
    answerHy: 'Այո, կփորձեմ ավելի շատ իսպաներեն խոսել։',
    tenseTag: 'Futuro Simple',
    timeContext: 'mañana',
  },
  {
    id: 'fut-14',
    category: 'futuro',
    number: 14,
    questionEs: '¿Viajarás este verano?',
    questionHy: 'Այս ամառ կճանապարհորդե՞ս։',
    answerEs: 'Sí, viajaré con mi familia.',
    answerHy: 'Այո, կճանապարհորդեմ ընտանիքիս հետ։',
    tenseTag: 'Futuro Simple',
    timeContext: 'este verano',
  },
  {
    id: 'fut-15',
    category: 'futuro',
    number: 15,
    questionEs: '¿Qué llevarás en la maleta?',
    questionHy: 'Ի՞նչ կվերցնես ճամպրուկում։',
    answerEs: 'Llevaré ropa, zapatos y mi teléfono.',
    answerHy: 'Կվերցնեմ հագուստ, կոշիկներ և հեռախոսս։',
    tenseTag: 'Futuro Simple',
  },
  {
    id: 'fut-16',
    category: 'futuro',
    number: 16,
    questionEs: '¿Dónde vivirás en el futuro?',
    questionHy: 'Ապագայում որտե՞ղ կապրես։',
    answerEs: 'Viviré en una ciudad grande.',
    answerHy: 'Կապրեմ մեծ քաղաքում։',
    tenseTag: 'Futuro Simple',
    timeContext: 'en el futuro',
  },
  {
    id: 'fut-17',
    category: 'futuro',
    number: 17,
    questionEs: '¿Qué aprenderás este año?',
    questionHy: 'Ի՞նչ կսովորես այս տարի։',
    answerEs: 'Aprenderé más español.',
    answerHy: 'Ավելի շատ իսպաներեն կսովորեմ։',
    tenseTag: 'Futuro Simple',
    timeContext: 'este año',
  },
  {
    id: 'fut-18',
    category: 'futuro',
    number: 18,
    questionEs: '¿Qué profesión tendrás en el futuro?',
    questionHy: 'Ապագայում ի՞նչ մասնագիտություն կունենաս։',
    answerEs: 'Todavía no lo sé, pero estudiaré mucho.',
    answerHy: 'Դեռ չգիտեմ, բայց շատ կսովորեմ։',
    tenseTag: 'Futuro Simple',
    timeContext: 'en el futuro',
  },
  {
    id: 'fut-19',
    category: 'futuro',
    number: 19,
    questionEs: '¿Qué harás durante las vacaciones?',
    questionHy: 'Ի՞նչ կանես արձակուրդների ընթացքում։',
    answerEs: 'Descansaré, viajaré y pasaré tiempo con mi familia.',
    answerHy: 'Կհանգստանամ, կճանապարհորդեմ և ժամանակ կանցկացնեմ ընտանիքիս հետ։',
    tenseTag: 'Futuro Simple',
    timeContext: 'durante las vacaciones',
  },
  {
    id: 'fut-20',
    category: 'futuro',
    number: 20,
    questionEs: '¿Cómo será tu día de mañana?',
    questionHy: 'Ինչպիսի՞ն կլինի քո վաղվա օրը։',
    answerEs: 'Será un día ocupado, pero interesante.',
    answerHy: 'Զբաղված, բայց հետաքրքիր օր կլինի։',
    tenseTag: 'Futuro Simple',
    timeContext: 'mañana',
  },

  // ================= TENSE DRILL COMPARISON (3) =================
  {
    id: 'drill-1',
    category: 'drill',
    number: 1,
    questionEs: '¿Qué haces hoy?',
    questionHy: 'Ի՞նչ ես անում այսօր։ (Presente)',
    answerEs: 'Hoy estudio y juego.',
    answerHy: 'Այսօր սովորում եմ և խաղում։',
    tenseTag: 'Presente',
    timeContext: 'Hoy',
  },
  {
    id: 'drill-2',
    category: 'drill',
    number: 2,
    questionEs: '¿Qué hiciste ayer?',
    questionHy: 'Ի՞նչ արեցիր երեկ։ (Pretérito Indefinido)',
    answerEs: 'Ayer estudié y jugué.',
    answerHy: 'Երեկ սովորեցի և խաղացի։',
    tenseTag: 'Pretérito Indefinido',
    timeContext: 'Ayer',
  },
  {
    id: 'drill-3',
    category: 'drill',
    number: 3,
    questionEs: '¿Qué harás mañana?',
    questionHy: 'Ի՞նչ կանես վաղը։ (Futuro Simple)',
    answerEs: 'Mañana estudiaré y jugaré.',
    answerHy: 'Վաղը կսովորեմ և կխաղամ։',
    tenseTag: 'Futuro Simple',
    timeContext: 'Mañana',
  },
];
